[theme]
base="light"
primaryColor="#2D7629"
secondaryBackgroundColor="#BBD1BA"
textColor="#000000"
font="serif"

[browser]
gatherUsageStats = false

[logger]
# Level of logging: 'error', 'warning', 'info', or 'debug'.
# Default: 'info'
level = "warning"
