[theme]
base="light"
primaryColor="#35495E"
secondaryBackgroundColor="#5BC0BE"
textColor="#333333"

[browser]
gatherUsageStats = false

[logger]
# Level of logging: 'error', 'warning', 'info', or 'debug'.
# Default: 'info'
level = "warning"
