[theme]
base="light"
primaryColor="#35495E"
secondaryBackgroundColor="#3365B2"
textColor="#000000"

[browser]
gatherUsageStats = false

[logger]
# Level of logging: 'error', 'warning', 'info', or 'debug'.
# Default: 'info'
level = "warning"
