SUPABASE_URL = "https://rbaawqpeyigwmzukrmvc.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJiYWF3cXBleWlnd216dWtybXZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTA0MzM0MjksImV4cCI6MjAwNjAwOTQyOX0.xF-nchgHwH1Xhyi18TfokUVjO2zYipw730IrESBvZ5A"
OPENAI_API_KEY = "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"
REPLICATE_API_KEY = "r8_3NSkiwpBKmC85pU61cXmYooqc35t5Ft0Dn5Cc"
HTTP_URL_COMMS = "https://prod-82.westus.logic.azure.com:443/workflows/161736b6d81f439096d0452bd1c9b082/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=5qrhisEBUZH0Okbxxl0686qdj9-UyNpVo4fELrELPf8" 
