SUPABASE_URL = "https://rbaawqpeyigwmzukrmvc.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJiYWF3cXBleWlnd216dWtybXZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTA0MzM0MjksImV4cCI6MjAwNjAwOTQyOX0.xF-nchgHwH1Xhyi18TfokUVjO2zYipw730IrESBvZ5A"
OPENAI_API_KEY = "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"
REPLICATE_API_KEY = "r8_3NSkiwpBKmC85pU61cXmYooqc35t5Ft0Dn5Cc"
